releases:
  - name: techradar
    chart: ./charts/{{`{{ .Release.Name }}`}}
    namespace: ra-{{`{{ .Environment.Name }}`}}-techradar
    missingFileHandler: Warn
    values:
    - config/values.yaml.gotmpl
    - config/{{`{{ .Environment.Name }}`}}.yaml