bases:
- environments.yaml
---
repositories:
- name: common
  url: https://bjw-s-labs.github.io/helm-charts

helmfiles:
- path: ./apps/techradar/helmfile.yaml
  values:
  - environments/{{ .Environment.Name }}/values.yaml
  - environments/{{ .Environment.Name }}/images.yaml
      