apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techradar-data-api-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: techradar-data-api
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        ConnectionStrings__TechRadarDatabase: {{ `"Host=techradar-postgres;Database=techradar;Username={{ .db_user }};Password={{ .db_password }}"` }}
        Identity__Authority: {{ `"{{ .authority }}"` }}
  data:
  - secretKey: authority
    remoteRef:
      key: secrets-k8/techradar/{{ .Values.env_name }}/auth
      property: authority
  - secretKey: db_user
    remoteRef:
      key: secrets-k8/techradar/{{ .Values.env_name }}/postgres
      property: user
  - secretKey: db_password
    remoteRef:
      key: secrets-k8/techradar/{{ .Values.env_name }}/postgres
      property: password